/* This file is part of the DeArrow Browser project - https://github.com/mini-bomba/DeArrowBrowser
*
*  Copyright (C) 2023-2025 mini_bomba
*  
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU Affero General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Affero General Public License for more details.
*
*  You should have received a copy of the GNU Affero General Public License
*  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
// NOTE: This file is the entrypoint to the 'app' binary.

use cloneable_errors::ErrorContext;
use components::async_task_manager::AsyncTaskManager;
use dearrow_browser_api::unsync::StatusResponse;
use gloo_console::error;
use reqwest::Url;
use std::rc::Rc;
use thumbnails::components::ThumbgenProvider;
use utils_common::api_request;
use web_sys::window;
use yew::prelude::*;
use yew_hooks::{use_async_with_options, use_interval, UseAsyncOptions};
use yew_router::prelude::*;

use contexts::*;
use pages::*;
use worker_client::WorkerProvider;
use yt_metadata::components::MetadataCacheProvider;

pub mod components;
pub mod constants;
pub mod contexts;
pub mod hooks;
pub mod settings;
pub mod utils_app;
pub mod utils_common;
pub mod pages;
#[path = "thumbnails/mod_app.rs"]
pub mod thumbnails;
pub mod sbserver;
pub mod worker_api;
pub mod worker_client;
#[path = "yt_metadata/mod_app.rs"]
pub mod yt_metadata;

#[function_component]
fn App() -> Html {
    let window_context = use_memo((), |()| {
        let window = window().expect("window should exist");
        WindowContext {
            origin: Url::parse(
                window.location().origin().expect("window.location.origin should exist").as_str()
            ).expect("window.location.origin should be a valid URL"),
        }
    });
    let update_clock = use_state(|| UpdateClock(false));

    let status = {
        let status_url = use_memo(window_context.clone(), |wc| wc.origin_join_segments(&["api", "status"]));
        use_async_with_options::<_, Rc<StatusResponse>, ErrorContext>(async move { 
            api_request::<_, StatusResponse>((*status_url).clone()).await
                .map(Rc::new)
                .inspect_err(|err| error!(format!("Failed to fetch status: {err:?}")))
        }, UseAsyncOptions::enable_auto())
    };
    {
        let status = status.clone();
        let update_clock = update_clock.clone();
        use_interval(move || {
            update_clock.set(UpdateClock(!update_clock.0));
            status.run();
        }, 60*1000);
    }

    html! {
        <ContextProvider<Rc<WindowContext>> context={window_context}>
        <ContextProvider<StatusContext> context={status.data.clone()}>
        <SettingsProvider>
        <WorkerProvider>
        <ThumbgenProvider>
        <MetadataCacheProvider>
        <ContextProvider<UpdateClock> context={*update_clock}>
        <AsyncTaskManager>
            <BrowserRouter>
                <Switch<MainRoute> render={render_main_route} />
            </BrowserRouter>
        </AsyncTaskManager>
        </ContextProvider<UpdateClock>>
        </MetadataCacheProvider>
        </ThumbgenProvider>
        </WorkerProvider>
        </SettingsProvider>
        </ContextProvider<StatusContext>>
        </ContextProvider<Rc<WindowContext>>>
    }
}

fn main() {
    yew::Renderer::<App>::new().render();
}

pub mod built_info {
    // Contents generated by buildscript, using built
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}
