[package]
name = "error_handling"
version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow = {version = "1.0.79", optional = true}
serde = {workspace = true, optional = true}

[lints]
workspace = true
